development:
  adapter: postgresql
  encoding: utf8
  database: portal_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: portal_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: portal_production
  pool: 5
